routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'AccueilController');
Route::resource('/profile', 'ProfileController');

Route::resource('/partner', 'PartnerController');

Auth::routes();

Route::resource('/register', 'RegisterController');
 
Route::get('/home', 'AccueilController@index')->name('home');

Route::get('/model', function(){
	return view('Pages.Model.index');
});

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    protected $fillable = ['height', 'intervalle', 'sexe', 'marital', 'religion', 'caste', 'pays', 'teint', 'domaine', 'user_id'];

    public function user(){
    	return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Flashy;
use App\Partner;
use App\Profile;
class PartnerController extends Controller
{
    public function __construct(){
        return $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profile = Profile::where('user_id', Auth::user()->id)->first();
        $partner = Partner::where('user_id', Auth::user()->id)->first();
        return view('Pages.Partner.index', compact(['partner', 'profile']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'height' => 'required|string',
            'intervalle' => 'required|string',
            'sexe' => 'required|string',
            'marital' => 'required|string',
            'religion' => 'required|string',
            'caste' => 'required|string',
            'pays' => 'required|string',
            'teint' => 'required|string',
            'domaine' => 'required|string'
            ]);
        Partner::create([
            'height' => $request->height,
            'intervalle' => $request->intervalle,
            'sexe' => $request->sexe,
            'marital' => $request->marital,
            'religion' => $request->religion,
            'caste' => $request->caste,
            'pays' => $request->pays,
            'teint' => $request->teint,
            'domaine' => $request->domaine,
            'user_id' => Auth::user()->id
            ]);
        Flashy::message('Information enregistrer avec succès');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'height' => 'required|string',
            'intervalle' => 'required|string',
            'sexe' => 'required|string',
            'marital' => 'required|string',
            'religion' => 'required|string',
            'caste' => 'required|string',
            'pays' => 'required|string',
            'teint' => 'required|string',
            'domaine' => 'required|string'
            ]);
        $update = Partner::findOrFail($id);
        $update->update([
            'height' => $request->height,
            'intervalle' => $request->intervalle,
            'sexe' => $request->sexe,
            'marital' => $request->marital,
            'religion' => $request->religion,
            'caste' => $request->caste,
            'pays' => $request->pays,
            'teint' => $request->teint,
            'domaine' => $request->domaine,
            'user_id' => Auth::user()->id
            ]);
        Flashy::message('Information modifier avec succès');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Pages/Partner/index.blade.php
@extends('Template.base', ['title' => "Information de partenaire desiré"])

@section('content')
	<div class="feedback">
		<div class="container">
			<h2>Completer vos information</h2>
			<p>Renseigner les informations de votre partenaire desiré pour completer votre profil.</p>
			<form action="{{ $a = ($partner) ? route('partner.update',$partner) : route('partner.store') }}" method="post" enctype="multipart/form-data" files="true">
				{{csrf_field()}}
				@if($partner)
					{{method_field('PUT')}}
				@endif
				<div class="col-md-6">
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Âge:</label>
						@php $i = 20 @endphp
						<select name="intervalle" required="">
							@if($partner)
								<option value="{{ $partner->intervalle }}">{{ $partner->intervalle }}</option>
							@endif
							@for ($i=20, $j = 25; $i < 70, $j < 70; $i+=5, $j+=5)   
								<option value="{{ $i.' - '.$j.' ans' }}">{{ $i.' - '.$j.' ans' }}</option>
							@endfor
						</select>
					</div>
					
					<div class="agileits">
						<label>Poids:</label>
						<select id="" class="frm-field required" required="" name="height">
							@if($partner)
								<option value="{{ $partner->height }}">{{ $partner->height }}</option>
							@endif
							@for ($j=10; $j < 150; $j+=5)
								<option value="{{$j.' KG'}}">{{$j.' KG'}}</option>
							@endfor
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Sexe:</label>
						<select id="" class="frm-field required" required="" name="sexe">  
							@if($partner)
								@if($partner->sexe == "m")
									<option value="m">Homme</option>   
									<option value="f">Femme</option>
								@else
									<option value="f">Femme</option>
									<option value="m">Homme</option>   
								@endif
							@else
							<option value="m">Homme</option>   
							<option value="f">Femme</option>
							@endif
							   
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Taille  :</label>
						<select id="" class="frm-field required" required="" name="caste">
							@if($partner)
								<option value="{{ $partner->caste }}">{{ $partner->caste }}</option>
							@endif
							@for ($i=10; $i < 100; $i+=5)
								<option value="{{'1m'.$i}}">1m{{$i}}</option>
							@endfor
								<option value="2m">2m</option>
						</select>
					</div>
					
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Réligion  :</label>
						<select id="" class="frm-field required" required="" name="religion">
							@if($partner)
								<option value="{{ $partner->religion }}">{{ ucfirst(strtoupper( $partner->religion ))}}</option>
							@endif  
							<option value="musulman">Musulman</option>   
							<option value="catholique">Catholique</option>   
							<option value="protestant">Prostestant</option>   
							<option value="autre">Autres</option>   
						</select>
					</div>
				</div>

				<div class="col-md-6">

					<div class="agileits">
						<label>Profession:</label>
						<input type="text" placeholder="Profession" required="required" name="domaine" value="{{$partner->domaine ?? old('domaine')}}" />
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Teint  :</label>
						<select id="" class="frm-field required" required="" name="teint">
							@if($partner)
								<option value="{{ $partner->teint }}">{{ $partner->teint }}</option>
							@endif  
							<option value="Noir">Noir</option>   
							<option value="Clair">Claire</option>   
							<option value="Brun">Brun</option>   
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Situation  :</label>
						<select id="" class="frm-field required" required="" name="marital"> 
							@if($partner)
								<option value="{{ $partner->marital }}">{{ $partner->marital }}</option>
							@endif 
							<option value="Celibataire">Célibataire</option>   
							<option value="Divorcer">Divorcer</option>   
							<option value="Veuve">Veuve</option>   
							<option value="Veufe">Veufe</option>   
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Pays  :</label>
						<input type="text" required="required" name="pays" placeholder="Guinée" value="{{$partner->pays ?? old('pays')}}" />
					</div>

					
				</div>
				<div class="clearfix"></div>

				<div class="w3_submit">
					<input type="submit" value="Enregistrer"/>
				</div>
			</form>
		</div>
	</div>
	<!-- section assistance -->
	<div class="agile-assisted-service text-center">
		<h4>Service Assistance</h4>
		<p>Our Relationship Managers have helped thousands of members find their life partners.</p>
		<a href="">Voir Plus</a>
	</div>
@stop