routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'AccueilController');
Route::resource('/profile', 'ProfileController');

Route::resource('/partner', 'PartnerController');

Auth::routes();

Route::resource('/register', 'RegisterController');
 
Route::get('/home', 'AccueilController@index')->name('home');

Route::get('/model', function(){
	return view('Pages.Model.index');
});

resources/views/Pages/UserProfile/index.blade.php
@extends('Template.base', ['title' => "Information Profile"])

@section('content')
	<div class="feedback">
		<div class="container">
			<h2>Renseigner votre profile</h2>
			<p>Renseigner tous les champs suivi (*) pour completer votre profil.</p>
			<form action="{{ $a= ($profile) ? route('profile.update',$profile) : route('profile.store') }}" method="post" enctype="multipart/form-data" files="true">
				{{csrf_field()}}
				@if($profile)
					{{method_field('PUT')}}
				@endif
				<div class="col-md-6">
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Nom:</label>
						<input type="text" placeholder="Nom de famille" name="nom" required="required" value="{{$profile->nom ?? old('nom')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Âge  :</label>
						<input type="date" required="required" name="age" value="{{$profile->age ?? old('age')}}"  />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Sexe:</label>
						<select id="" class="frm-field required" required="" name="sexe">  
							<option value="m">Homme</option>   
							<option value="f">Femme</option>   
						</select>
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Taille  :</label>
						<select id="" class="frm-field required" required="" name="taille">
							@for ($i=10; $i < 100; $i++)
								<option value="{{'1m'.$i}}">1m{{$i}}</option>
							@endfor
								<option value="2m">2m</option>
						</select>
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Profession  :</label>
						<input type="text" required="required" name="profession" placeholder="Informaticien" value="{{$profile->profession ?? old('profession')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Pays  :</label>
						<input type="text" required="required" name="pays" placeholder="Guinée" value="{{$profile->pays ?? old('pays')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Contact  :</label>
						<input type="text" required="required" name="tel" placeholder="660025241" value="{{$profile->tel ?? old('tel')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Réligion  :</label>
						<select id="" class="frm-field required" required="" name="religion">  
							<option value="musulman">Musulman</option>   
							<option value="catholique">Catholique</option>   
							<option value="protestant">Prostestant</option>   
							<option value="autre">Autres</option>   
						</select>
					</div>
				</div>
				<div class="col-md-6">
					<div class="agileits">
						<label>Prénom:</label>
						<input type="text" placeholder="Prénom" required="required" name="prenom" value="{{$profile->prenom ?? old('prenom')}}" />
					</div>
					<div class="agileits">
						<label>Adresse:</label>
						<input type="text" placeholder="Adresse" name="adresse" required="required" value="{{$profile->adresse ?? old('adresse')}}"/>
					</div>
					
					<div class="agileits">
						<label>Poids:</label>
						<select id="" class="frm-field required" required="" name="poids">
							@for ($j=10; $j < 150; $j++)
								<option value="{{$j.' KG'}}">{{$j.' KG'}}</option>
							@endfor
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Teint  :</label>
						<select id="" class="frm-field required" required="" name="teint">  
							<option value="Noir">Noir</option>   
							<option value="Clair">Claire</option>   
							<option value="Brun">Brun</option>   
						</select>
					</div>

					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Nationalité  :</label>
						<input type="text" required="required" name="nationalite" placeholder="Guinéenne" value="{{$profile->nationalite ?? old('nationalite')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Photo  :</label>
						<input type="file" name="avatar" value="{{$profile->avatar ?? old('avatar')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;"></span>E-mail  :</label>
						<input type="text" name="email" placeholder="info@gmail.com" value="{{$profile->email ?? old('email')}}" />
					</div>
					<div class="agileits">
						<label><span style="color:red;font-weight: 100;">*</span>Situation  :</label>
						<select id="" class="frm-field required" required="" name="situation">  
							<option value="Marier">Marié</option>   
							<option value="Celibataire">Célibataire</option>   
							<option value="Divorcer">Divorcer</option>   
							<option value="Veuve">Veuve</option>   
							<option value="Veufe">Veufe</option>   
						</select>
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-12 w3_feedbacktextmessage">
					<label><span style="color:red;font-weight: 100;">*</span>A Propos de vous:</label>
					<textarea name="about" placeholder=""> {{$profile->about ?? old('about')}} </textarea>
				</div>
				<div class="clearfix"></div>
				<div class="w3_submit">
					<input type="submit" value="Enregistrer"/>
				</div>
			</form>
		</div>
	</div>
	<!-- section assistance -->
	<div class="agile-assisted-service text-center">
		<h4>Service Assistance</h4>
		<p>Our Relationship Managers have helped thousands of members find their life partners.</p>
		<a href="">Voir Plus</a>
	</div>
@stop

resources/views/Pages/UserProfile/show.blade.php
@extends('Template.base', ['title' => "Mon Profile"])

@section('content')
	<!-- information du profile -->
	<div class="w3ls-list">
		<div class="container">
		<h2>Profile de {{ $profile->nom.' '. $profile->prenom }}</h2>
		<div class="col-md-9 profiles-list-agileits">
			<div class="single_w3_profile">
				<div class="agileits_profile_image">
					<img src="{{asset($profile->avatar)}}" alt="{{$profile->nom}} image" width="260" height="280" />
				</div>
				<div class="w3layouts_details">
					<h4>Profile ID : {{$profile->profile}}</h4>
					<span>Compte créer il y a {{ Date::make($profile->created_at)->diffForHumans() }}.</span>
					<p>{{Date::make($profile->age)->until()}} , {{$profile->poids}}, {{$profile->taille}}, {{$a = ($profile->sexe == 'm') ? 'Homme' : 'Femme'}}, {{$profile->nationalite}} .</p>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="profile_w3layouts_details">
				<div class="agileits_aboutme">
					<div class="row">
						<div class="col-sm-12">
							<a class="btn btn-info" href="{{ route('profile.show',$profile) }}">Mon profile</a>
							<a class="btn btn-info" href="{{ url('/profile') }}">Modifier mon profile</a>
							<a class="btn btn-info" href="{{ url('/partner') }}">Mon Futur partenaire</a>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<!-- information générale -->
							<h5>Information Générale:</h5>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Nom : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->nom.' '.$profile->prenom}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Adresse : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->adresse}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Âge : </label>
									<div class="col-sm-6 w3_details">
										{{Date::make($profile->age)->until()}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Poids : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->poids}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Taille : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->taille}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Teint : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->teint}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Profession : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->profession}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Sexe : </label>
									<div class="col-sm-6 w3_details">
										{{$a = ($profile->sexe == 'm') ? 'Homme' : 'Femme'}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Nationalité : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->nationalite}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Pays : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->pays}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Réligion : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->religion}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Statut Matrimoniale : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->situation}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Profile ID : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->profile}}
									</div>
									<div class="clearfix"> </div>
								</div>
						</div>
						<div class="col-sm-6 pull-right">
							<!-- détail de la personne désiré -->
							<h5>Partenaire désiré :</h5>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Age : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->intervalle ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Sexe : </label>
									<div class="col-sm-6 w3_details">
										{{ '' ?? ($a = ($profile->user->partner->sexe == "m" ) ? "Homme" : "Femme" ) }}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Taille : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->caste  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Statut matrimoniale : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->marital  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Religion : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->religion  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Poids : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->height  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Profession : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->domaine  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Teint : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->teint  ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="form_but1">
									<label class="col-sm-6 control-label1">Pays : </label>
									<div class="col-sm-6 w3_details">
										{{$profile->user->partner->pays ?? ''}}
									</div>
									<div class="clearfix"> </div>
								</div>
						</div>
					</div>

				</div>
			</div>
		</div>
		<div class="col-md-3 w3ls-aside">
			<h3>Réchercher par Profile ID:</h3>
			<form action="#" method="get"> 
				<input class="text" type="text" name="profile_id" placeholder="Saisir l'ID du Profile" required="">
				<input type="submit" value="Search">
				<div class="clearfix"></div>
			</form>
			<div class="view_profile">
        	<h3>Profiles Similaires</h3>
        	<ul class="profile_item">
        	  	<a href="#">
	        	   	<li class="profile_item-img">
	        	   	  	<img src="images/p1.jpg" class="img-responsive" alt="">
	        	   	</li>
	        	   	<li class="profile_item-desc">
	        	   	  	<h6>ID : 2458741</h6>
	        	   	  	<p>29 Yrs, 5Ft 5in Christian
					  	MBA/PGDM,
					  	Rs 10 - 15 lac Mark...</p>
	        	   	</li>
	        	   	<div class="clearfix"> </div>
        	  	</a>
           </ul>
       </div>
		</div>
		<div class="clearfix"></div>
		</div>
			<!-- Modal -->
		<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
		  <div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
			  <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Login to Continue</h4>
			  </div>
			  <div class="modal-body">
				<div class="login-w3ls">
					<form id="signin" action="#" method="post">
						<label>User Name </label>
						<input type="text" name="User Name" placeholder="Username" required="">
						<label>Password</label>
						<input type="password" name="Password" placeholder="Password" required="">	
						<div class="w3ls-loginr"> 
							<input type="checkbox" id="brand" name="checkbox" value="">
							<span> Remember me ?</span> 
							<a href="#">Forgot password ?</a>
						</div>
						<div class="clearfix"> </div>
						<input type="submit" name="submit" value="Login">
						<div class="clearfix"> </div>
						<div class="social-icons">
							<ul>  
								<li><a href="#"><span class="icons"><i class="fa fa-facebook" aria-hidden="true"></i></span><span class="text">Facebook</span></a></li> 
								<li class="twt"><a href="#"><span class="icons"><i class="fa fa-twitter" aria-hidden="true"></i></span><span class="text">Twitter</span></a></li>  
							</ul> 
							<div class="clearfix"> </div>
						</div>	
					</form>
				</div>
			  </div>
			</div>

		  </div>
		</div>
			<!-- //Modal -->
	</div>
	<!-- section assistance -->
	<div class="agile-assisted-service text-center">
		<h4>Service Assistance</h4>
		<p>Our Relationship Managers have helped thousands of members find their life partners.</p>
		<a href="">Voir Plus</a>
	</div>
@stop